// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231119181801_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Electronic"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Shoes"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 2,
                            ImageUrl = "/images/1.jpg",
                            Price = 12700m,
                            ProductName = "Computer",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            ImageUrl = "/images/2.jpg",
                            Price = 20222m,
                            ProductName = "Phone",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2,
                            ImageUrl = "/images/3.jpg",
                            Price = 15000m,
                            ProductName = "Notebook",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 3,
                            ImageUrl = "/images/4.jpg",
                            Price = 100m,
                            ProductName = "Adidas",
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            ImageUrl = "/images/5.jpg",
                            Price = 120m,
                            ProductName = "Envar Paşa Hatıraları",
                            Summary = ""
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
